services:
  postgres:
    image: postgres:16.6
    container_name: db-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    networks:
      - postgres-network

  adminer:
    image: adminer
    container_name: db-adminer
    ports:
      - 3000:8080
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
